version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:5000"  # External port 8080 maps to internal Flask port 5000
    volumes:
      - ./data:/data
    restart: unless-stopped
    environment:
      - DB_PATH=/data/scan_results.db
      - PYTHONUNBUFFERED=1
      - ZAP_HOST=zap
      - ZAP_PORT=8080
    networks:
      - zap-network
    depends_on:
      - zap
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/statistics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    container_name: zap_proxy
    ports:
      - "8090:8080"  # ZAP web interface
    environment:
      - ZAP_PORT=8080
    command: >
      bash -c "
      /zap/zap.sh -daemon
      -host 0.0.0.0
      -port 8080
      -config api.addrs.addr.name=.*
      -config api.addrs.addr.regex=true
      -config api.key=zap-api-key-12345
      "
    networks:
      - zap-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/JSON/core/view/version/?apikey=zap-api-key-12345"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  zap-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
